# Sample configuration file for Mulch server (mulchd)
# Values here are defaults (except for seeds)

# Listen address of Mulchd API server (no IP = all interfaces)
listen = ":8585"

# URI libvirt will use to contact the hypervisor
libvirt_uri = "qemu:///system"

# Storage path for libvirt disk images and "seeds" (Linux distributions)
# real world example: /srv/mulch
storage_path = "./var/storage"

# Mulch server (small) databases
# real world example: /var/lib/mulch
data_path = "./var/data"

# Temporary files path, empty = system default directory
# (may be useful for big backups compression)
temp_path = ""

# Name prefix for Mulch VMs in libirt (so we don't collide with
# some existing VMs)
vm_prefix = "mulch-"

# This user will be created with VMs as a sudoers, and used for
# control and command of the VM by Mulch
mulch_super_user = "admin"

# Listen address for SSH proxy
proxy_listen_ssh = ":8022"

# ACME protocol directory server
#
# We use Let's Encrypt *staging* directory by default.
# See https://letsencrypt.org/docs/staging-environment/ to get the
# staging "Fake LE Root X1" root certificate during tests.
#
# For Let's Encrypt production URL, you can use:
# proxy_acme_url = "LETS_ENCRYPT_PRODUCTION"
proxy_acme_url = "https://acme-staging.api.letsencrypt.org/directory"

# Email will be used by CAs, such as Let's Encrypt, to notify about
# problems with issued certificates.
proxy_acme_email = "root@localhost.localdomain"

# Listen addresses (HTTP/HTTPS) for the Resverse Proxy
proxy_listen_http = ":80"
proxy_listen_https = ":443"

# Sample seeds
[[seed]]
name = "debian_9"
current_url = "http://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2"
as = "debian-9-openstack-amd64.qcow2"

[[seed]]
name = "centos_7"
current_url = "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
as = "centos-7-x86_64.qcow2"

[[seed]]
name = "ubuntu_1810"
current_url = "http://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-amd64.img"
as = "ubuntu-1810-amd64.qcow2"
