# Sample configuration file for Mulch server (mulchd)
# Values here are defaults (except for seeds)

# Listen address of Mulchd API server (no IP = all interfaces)
listen = ":8686"

# Enable HTTPS-only for *API server*, using a Let's Encrypt certificate
# with specified domain. Default ("") is HTTP-only.
# See also proxy_acme_* settings below since the certificate is generated
# by mulch-proxy (port 443)
listen_https_domain = ""

# URI libvirt will use to contact the hypervisor
libvirt_uri = "qemu:///system"

# Storage path for libvirt disk images and "seeds" (Linux distributions)
# real world example: /srv/mulch
storage_path = "./var/storage"

# Mulch server (small) databases
# real world example: /var/lib/mulch
data_path = "./var/data"

# Temporary files path, empty = system default directory
# (may be useful for big backups compression, backup uploads, etc)
temp_path = ""

# Name prefix for Mulch VMs in libirt (so we don't collide with
# some existing VMs)
vm_prefix = "mulch-"

# This user will be created with VMs as a sudoers, and used for
# control and command of the VM by Mulch
mulch_super_user = "admin"

# Listen address for SSH proxy
proxy_listen_ssh = ":8022"

# Extra (limited) SSH pub keys (see ./etc/extra_authorized_keys.sample)
proxy_ssh_extra_keys_file = ""

# ACME protocol directory server
#
# We use Let's Encrypt *staging* directory by default.
# See https://letsencrypt.org/docs/staging-environment/ to get the
# staging "Fake LE Root X1" root certificate during tests.
#
# For Let's Encrypt production URL, you can use this "magic constant":
# proxy_acme_url = "LETS_ENCRYPT_PRODUCTION"
# Warning: define a proper email below!
# Warning: you may have to clear ./data/certs/ directory if you change this setting
proxy_acme_url = "https://acme-staging.api.letsencrypt.org/directory"

# Email will be used by CAs, such as Let's Encrypt, to notify about
# problems with issued certificates.
proxy_acme_email = "root@localhost.localdomain"

# Listen addresses (HTTP/HTTPS) for the Resverse Proxy
proxy_listen_http = ":80"
proxy_listen_https = ":443"

# Auto-rebuild will check everyday, at specified time, if any VM need
# an automatic rebuild (according its settings). Format: HH:MM
auto_rebuild_time = "23:30"

# Sample seeds
[[seed]]
name = "debian_9"
current_url = "http://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2"
as = "debian-9-openstack-amd64.qcow2"

[[seed]]
name = "centos_7"
current_url = "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
as = "centos-7-x86_64.qcow2"

[[seed]]
name = "ubuntu_1810"
current_url = "http://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-amd64.img"
as = "ubuntu-1810-amd64.qcow2"

[[seed]]
name = "ubuntu_1904"
current_url = "http://cloud-images.ubuntu.com/disco/current/disco-server-cloudimg-amd64.img"
as = "ubuntu-1904-amd64.qcow2"
