# This is a (working) minimalist sample VM definition

# Usage:
#  mulch vm create sample-vm-simple.toml

name = "simple"
hostname = "simple.localdomain"

seed = "debian_9"

# Will speed up creation for this test (no update/upgrade)
# (but install will not be up to date, don't do this in production!)
init_upgrade = false

disk_size = "20G"
ram_size = "1G"
cpu_count = 1


# Dev test, will be changed soon
domains = ['test1.localhost->1234', 'dev.localhost->8080']
redirect_to_https = false
#redirect_to_https = true # (false = proxy also from tcp/80)
redirects = [
    ["www.test1.localhost", "test1.localhost"],
]
