name = "centos_7_lamp"
hostname = "lamp"

seed = "centos_7"

disk_size = "8G"
ram_size = "2G"
cpu_count = 1

auto_rebuild = "daily"

prepare_prefix_url = "https://raw.githubusercontent.com/OnitiFR/mulch/master/scripts/prepare/"
prepare = [
    "admin@seeders/rh-comfort.sh",
    "admin@seeders/rh-lamp.sh",
]
