# This is a sample VM creating a new instance from a backup

# Usage:
#  mulch vm create sample-vm-restore.toml

name = "restore"
hostname = "testvm.localdomain"

seed = "debian_9"

init_upgrade = true

disk_size = "20G"
ram_size = "2G"
cpu_count = 1

backup_disk_size = "2G"

prepare_prefix_url = "https://raw.githubusercontent.com/Xfennec/mulch/master/scripts/prepare/"
prepare = [
    "admin@deb-comfort.sh",
    "admin@deb-lamp.sh",
]

backup_prefix_url = "https://raw.githubusercontent.com/Xfennec/mulch/master/scripts/backup/"
backup = [
    "app@lamp.sh",
]

restore_backup = "test.qcow2c"
restore_prefix_url = "https://raw.githubusercontent.com/Xfennec/mulch/master/scripts/restore/"
restore = [
    "app@wordpress.sh",
]
